branch-defaults:
  dev:
    environment: QrlaApi-env
environment-defaults:
  QrlaApi-env:
    branch: null
    repository: null
global:
  application_name: qrlaApi
  default_ec2_keyname: QRLA-prod
  default_platform: PHP 8.2 running on 64bit Amazon Linux 2023
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
